local addonName, addon = ...

addon.emoteList = {
    "agree", "amaze", "angry", "apologize", "applaud", "attacktarget", 
    "bark", "bashful", "beckon", "beg", "belch", "bite", "bleed", "blink", "blow", "blush", "boggle", "bonk", "bored", "bounce", "bow", "bravo", "brandish", "brb", "burp", "bye", 
    "cackle", "calm", "cat", "charge", "cheer", "chew", "chicken", "chuckle", "clap", "cold", "comfort", "commend", "confused", "congrats", "cough", "cower", "crack", "cringe", "cry", "cuddle", "curious", "curtsey", 
    "dance", "ding", "disappointed", "doh", "doom", "drink", "drool", "duck", 
    "eat", "excited", 
    "facepalm", "farewell", "fart", 
    "fear", "feast", "fidget", "flap", "flee", "flex", "flirt", "flop", "followme", "food", "frown", 
    "gasp", "gaze", "giggle", "glad", "glare", "gloat", "golfclap", "goodbye", "greet", "grin", "groan", "grovel", "growl", "guffaw", 
    "hail", "happy", "healme", "hello", "helpme", "hi", "highfive", "hug", "hungry", 
    "impatient", "incoming", "insult", "introduce", 
    "jk", 
    "kiss", "kneel", "knuckles", 
    "laugh", "lavish", "lay", "lick", "lie", "listen", "lol", "lost", "love", 
    "mad", "massage", "moan", "mock", "moo", "moon", "mountspecial", "mourn", 
    "no", "nod", "nosepick",
    "oom", 
    "panic", "pat", "peer", "peon", "pick", "pizza", "plead", "point", "poke", "ponder", "pounce", "praise", "pray", "purr", "puzzled", 
    "question", 
    "raise", "rasp", "ready", "read", "rear", "regret", "roar", "rofl", "rolleyes", "rude", 
    "salute", "scared", "scratch", "sexy", "shake", "shimmy", "shindig", "shiver", "shoo", "shrug", "shy", "sigh", "silly", "slap", "sleep", "smell", "smile", "smirk", "snarl", "snicker", "sniff", "snub", "sob", "soothe", "sorry", "spit", "spoon", "stare", "stink", "strong", "strut", "surprised", "surrender", 
    "talk", "talkex", "talkq", "tap", "taunt", "tease", "thanks", "think", "thirsty", "threat", "tickle", "tired", "train", "ty", 
    "veto", "victory", "violin", "volunteer", 
    "wait", "wave", "weep", "welcome", "whine", "whistle", "whoa", "wicked", "wink", "woot", "work", "wrath", 
    "yawn", "yay", "yes", "yw"}